@extends('admin.layouts.admin')

@section('title', 'TripWise — Performance Reports')

@section('content')
<!-- Breadcrumb -->
<div class="breadcrumb">
    <a href="{{ route('admin.dashboard') }}">Home</a>
    <span>/</span>
    <a href="{{ route('admin.performance.index') }}">Performance Management</a>
    <span>/</span>
    <span>Performance Reports</span>
</div>

<!-- Page Header -->
<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem;">
    <div>
        <h1 style="font-size:1.75rem;color:var(--primary);margin:0 0 0.25rem;">Performance Reports</h1>
        <p style="color:var(--text-muted);font-size:0.9rem;margin:0;">Generate and manage performance reports for administrators.</p>
    </div>
    <div style="display:flex;gap:0.75rem;flex-wrap:wrap;">
        <a href="{{ route('admin.performance.reports.export', ['format' => 'pdf']) }}" target="_blank" class="btn btn-secondary"><i class="fas fa-file-pdf"></i> Export PDF</a>
        <a href="{{ route('admin.performance.reports.export', ['format' => 'csv']) }}" class="btn btn-secondary"><i class="fas fa-file-excel"></i> Export Excel</a>
        <a href="{{ route('admin.drivers.documents') }}" class="btn btn-primary"><i class="fas fa-folder-open"></i> Print Report</a>
    </div>
</div>

<!-- Dashboard Stats Cards -->
<div class="summary-grid">
    <div class="summary-card">
        <div class="card-icon blue"><i class="fas fa-file-alt"></i></div>
        <div class="card-info">
            <h3>{{ $stats['generated'] }}</h3>
            <p>Reports Generated</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon green"><i class="fas fa-user"></i></div>
        <div class="card-info">
            <h3>{{ $stats['individual'] }}</h3>
            <p>Individual Reports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon orange"><i class="fas fa-ranking-star"></i></div>
        <div class="card-info">
            <h3>{{ $stats['ranking'] }}</h3>
            <p>Ranking Reports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon purple"><i class="fas fa-bullseye"></i></div>
        <div class="card-info">
            <h3>{{ $stats['kpi'] }}</h3>
            <p>KPI Reports</p>
        </div>
    </div>
</div>

<!-- Filters -->
<div class="table-card" style="margin-bottom:1rem;">
    <form method="GET" action="{{ route('admin.performance.reports') }}" style="display:flex;gap:1rem;align-items:flex-end;flex-wrap:wrap;">
        <div style="flex:1;min-width:200px;">
            <label style="display:block;font-size:0.85rem;font-weight:600;margin-bottom:0.4rem;">Search Reports</label>
            <input type="text" name="search" value="{{ request('search') }}" placeholder="Search by report name..." style="width:100%;padding:0.6rem 1rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.9rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;">
        </div>
        <div style="min-width:180px;">
            <label style="display:block;font-size:0.85rem;font-weight:600;margin-bottom:0.4rem;">Report Type</label>
            <select name="type" style="width:100%;padding:0.6rem 1rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.9rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;">
                <option value="">All Types</option>
                <option value="individual" {{ request('type') === 'individual' ? 'selected' : '' }}>Individual</option>
                <option value="department" {{ request('type') === 'department' ? 'selected' : '' }}>Department</option>
                <option value="ranking" {{ request('type') === 'ranking' ? 'selected' : '' }}>Ranking</option>
                <option value="kpi" {{ request('type') === 'kpi' ? 'selected' : '' }}>KPI</option>
                <option value="safety" {{ request('type') === 'safety' ? 'selected' : '' }}>Safety</option>
                <option value="attendance" {{ request('type') === 'attendance' ? 'selected' : '' }}>Attendance</option>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary"><i class="fas fa-search"></i> Filter</button>
    </form>
</div>

<!-- Reports Table -->
<div class="table-card">
    <h3 style="margin:0 0 1rem;"><i class="fas fa-file-alt"></i> Report History</h3>
    <div style="overflow-x:auto;">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Report Name</th>
                    <th>Report Type</th>
                    <th>Generated Date</th>
                    <th>Generated By</th>
                    <th>Status</th>
                    <th style="text-align:right;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($drivers as $driver)
                    <tr>
                        <td>#RPT-DRV-{{ str_pad($driver->id, 5, '0', STR_PAD_LEFT) }}</td>
                        <td>
                            <a href="{{ route('admin.drivers.profile', $driver->id) }}" style="display:flex;align-items:center;gap:0.5rem;color:inherit;text-decoration:none;">
                                <img src="{{ $driver->photo ?: asset('drivers/photo/' . $driver->id) }}" alt="{{ $driver->first_name }}" style="width:32px;height:32px;border-radius:50%;object-fit:cover;">
                                <div>
                                    <strong>{{ $driver->full_name }} — Performance Report</strong>
                                    <div style="font-size:0.75rem;color:var(--text-muted);">Driver ID: {{ $driver->formatted_id }}</div>
                                </div>
                            </a>
                        </td>
                        <td style="text-transform:capitalize;">Individual Evaluation</td>
                        <td>{{ $driver->updated_at ? $driver->updated_at->format('M d, Y h:i A') : 'Aug 11, 2026 09:00 AM' }}</td>
                        <td>System Admin</td>
                        <td>
                            <span class="item-badge badge-success">
                                Generated
                            </span>
                        </td>
                        <td style="text-align:right;">
                            <div style="display:flex;gap:0.35rem;justify-content:flex-end;">
                                <a href="{{ route('admin.drivers.profile', ['id' => $driver->id, 'tab' => 'tab-performance']) }}" class="btn btn-sm btn-secondary" title="View Full Report"><i class="fas fa-eye"></i></a>
                                <a href="{{ route('admin.drivers.documents.download', $driver->id) }}" class="btn btn-sm btn-primary" title="Download Document PDF"><i class="fas fa-file-pdf"></i></a>
                                <button class="btn btn-sm btn-secondary" title="Print Report" onclick="window.print()"><i class="fas fa-print"></i></button>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr><td colspan="7" style="text-align:center;color:var(--text-muted);padding:2rem;">No driver performance reports found.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div style="margin-top:1rem;">
        {{ $drivers->links() }}
    </div>
</div>

<!-- Toast -->
<div id="toast" style="display:none;position:fixed;bottom:1.5rem;right:1.5rem;background:var(--charcoal);color:#fff;padding:0.75rem 1.25rem;border-radius:0.75rem;box-shadow:0 8px 20px rgba(0,0,0,0.2);z-index:3000;align-items:center;gap:0.75rem;font-size:0.85rem;font-family:'Inter',sans-serif;">
    <i class="fas fa-check-circle" style="color:var(--success);"></i>
    <span id="toastMessage"></span>
</div>

<!-- Charts -->
<div class="charts-grid" style="margin-top:1.5rem;">
    <div class="chart-card">
        <h3><i class="fas fa-chart-bar"></i> Monthly Performance Reports</h3>
        <div class="chart-wrapper">
            <canvas id="monthlyReportsChart"></canvas>
        </div>
    </div>
    <div class="chart-card">
        <h3><i class="fas fa-chart-line"></i> Report Generation Trend</h3>
        <div class="chart-wrapper">
            <canvas id="reportTrendChart"></canvas>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
function exportReport(format) { showToast('Exporting ' + format.toUpperCase() + ' report...'); }
function showToast(message) {
    const toast = document.getElementById('toast');
    document.getElementById('toastMessage').textContent = message;
    toast.style.display = 'flex';
    setTimeout(() => { toast.style.display = 'none'; }, 3000);
}
document.addEventListener('DOMContentLoaded', function() {
    const chartDefaults = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { labels: { font: { family: "'Poppins', sans-serif" } } } }
    };

    new Chart(document.getElementById('monthlyReportsChart'), {
        type: 'bar',
        data: {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            datasets: [{
                label: 'Reports',
                data: [5, 8, 6, 9, 7, 10],
                backgroundColor: '#F44336',
                borderRadius: 8
            }]
        },
        options: { ...chartDefaults, scales: { y: { beginAtZero: true } } }
    });

    new Chart(document.getElementById('reportTrendChart'), {
        type: 'line',
        data: {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            datasets: [{
                label: 'Reports Generated',
                data: [5, 8, 6, 9, 7, 10],
                borderColor: '#3b82f6',
                backgroundColor: 'rgba(59,130,246,0.1)',
                fill: true, tension: 0.4, pointRadius: 4, pointBackgroundColor: '#3b82f6'
            }]
        },
        options: { ...chartDefaults, plugins: { legend: { display: false } } }
    });
});
</script>
@endsection
