@extends('admin.layouts.admin')

@section('title', 'TripWise — Export Center')

@section('content')
<!-- Breadcrumb -->
<div class="breadcrumb">
    <a href="{{ route('admin.dashboard') }}">Home</a>
    <span>/</span>
    <a href="{{ route('admin.reports.index') }}">Reports & Analytics</a>
    <span>/</span>
    <span>Export Center</span>
</div>

<!-- Page Header -->
<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem;">
    <div>
        <h1 style="font-size:1.75rem;color:var(--primary);margin:0 0 0.25rem;">Export Center</h1>
        <p style="color:var(--text-muted);font-size:0.9rem;margin:0;">Manage report exports, scheduled exports, custom report builder, and export history.</p>
    </div>
    <div style="display:flex;gap:0.75rem;flex-wrap:wrap;">
        <button class="btn btn-secondary" onclick="showToast('Scheduled exports feature coming soon')"><i class="fas fa-clock"></i> Scheduled Reports</button>
        <button class="btn btn-primary" onclick="showToast('Custom report builder coming soon')"><i class="fas fa-magic"></i> Custom Report Builder</button>
    </div>
</div>

<!-- Dashboard Stats Cards -->
<div class="summary-grid">
    <div class="summary-card">
        <div class="card-icon blue"><i class="fas fa-download"></i></div>
        <div class="card-info">
            <h3>{{ $stats['total_exports'] }}</h3>
            <p>Total Exports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon green"><i class="fas fa-file-pdf"></i></div>
        <div class="card-info">
            <h3>{{ $stats['pdf_exports'] }}</h3>
            <p>PDF Exports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon orange"><i class="fas fa-file-excel"></i></div>
        <div class="card-info">
            <h3>{{ $stats['excel_exports'] }}</h3>
            <p>Excel Exports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon purple"><i class="fas fa-print"></i></div>
        <div class="card-info">
            <h3>{{ $stats['printed_reports'] }}</h3>
            <p>Printed Reports</p>
        </div>
    </div>
</div>

<!-- Filters -->
<div class="table-card" style="margin-bottom:1.5rem;padding:1rem 1.25rem;">
    <form method="GET" action="{{ route('admin.reports.export-center') }}" class="filter-bar" style="margin-bottom:0;flex-wrap:wrap;">
        <input type="text" name="search" placeholder="Search exports..." value="{{ request('search') }}" style="padding:0.5rem 0.85rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.85rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;min-width:200px;">
        <select name="format" style="padding:0.5rem 0.85rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.85rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;min-width:140px;">
            <option value="">All Formats</option>
            <option value="pdf" {{ request('format') === 'pdf' ? 'selected' : '' }}>PDF</option>
            <option value="excel" {{ request('format') === 'excel' ? 'selected' : '' }}>Excel</option>
            <option value="print" {{ request('format') === 'print' ? 'selected' : '' }}>Print</option>
        </select>
        <div style="margin-left:auto;display:flex;gap:0.5rem;">
            <button type="submit" class="btn btn-primary" style="padding:0.5rem 1rem;font-size:0.85rem;"><i class="fas fa-search"></i> Search</button>
            <a href="{{ route('admin.reports.export-center') }}" class="btn btn-secondary" style="padding:0.5rem 1rem;font-size:0.85rem;"><i class="fas fa-undo"></i> Reset</a>
        </div>
    </form>
</div>

<!-- Exports Table -->
<div class="table-card">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;flex-wrap:wrap;gap:0.75rem;">
        <h3 style="margin:0;"><i class="fas fa-list"></i> Export History</h3>
        <span style="font-size:0.85rem;color:var(--text-muted);">Showing {{ $exports->firstItem() ?? 0 }} to {{ $exports->lastItem() ?? 0 }} of {{ $exports->total() }} results</span>
    </div>
    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Export Format</th>
                    <th>Generated By</th>
                    <th>Export Date</th>
                    <th>Status</th>
                    <th style="text-align:center;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($exports as $export)
                <tr>
                    <td><strong>{{ $export->report->name ?? 'Report #' . $export->report_id }}</strong></td>
                    <td>
                        @php
                            $formatColors = ['pdf' => 'status-pending', 'excel' => 'status-success', 'print' => 'status-review'];
                        @endphp
                        <span class="status-badge {{ $formatColors[$export->export_format] ?? 'status-pending' }}">{{ strtoupper($export->export_format) }}</span>
                    </td>
                    <td>{{ $export->exportedBy->name ?? 'System' }}</td>
                    <td>{{ $export->exported_at ? $export->exported_at->format('M d, Y H:i') : '-' }}</td>
                    <td><span class="status-badge status-{{ $export->status === 'completed' ? 'success' : ($export->status === 'pending' ? 'pending' : 'review') }}">{{ ucfirst($export->status) }}</span></td>
                    <td style="text-align:center;">
                        <button class="icon-btn" title="Download" onclick="showToast('Downloading export...')"><i class="fas fa-download"></i></button>
                        <button class="icon-btn" title="Print" onclick="showToast('Printing...')"><i class="fas fa-print"></i></button>
                        <button class="icon-btn" title="Delete" onclick="deleteExport({{ $export->id }})" style="color:var(--danger);"><i class="fas fa-trash"></i></button>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" style="text-align:center;padding:2rem;color:var(--text-muted);">No exports found.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div style="margin-top:1rem;display:flex;justify-content:center;">
        {{ $exports->links() }}
    </div>
</div>

@endsection

@push('scripts')
<script>
function deleteExport(id) {
    if (confirm('Are you sure you want to delete this export?')) {
        showToast('Export deleted successfully.');
    }
}
</script>
@endpush
