@extends('admin.layouts.admin')

@section('title', 'TripWise — Report History')

@section('content')
<!-- Breadcrumb -->
<div class="breadcrumb">
    <a href="{{ route('admin.dashboard') }}">Home</a>
    <span>/</span>
    <a href="{{ route('admin.reports.index') }}">Reports & Analytics</a>
    <span>/</span>
    <span>Report History</span>
</div>

<!-- Page Header -->
<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem;">
    <div>
        <h1 style="font-size:1.75rem;color:var(--primary);margin:0 0 0.25rem;">Report History</h1>
        <p style="color:var(--text-muted);font-size:0.9rem;margin:0;">Complete history of all generated reports, downloads, exports, and audit trail.</p>
    </div>
    <button class="btn btn-secondary" onclick="exportReport('excel')"><i class="fas fa-download"></i> Export History</button>
</div>

<!-- Dashboard Stats Cards -->
<div class="summary-grid">
    <div class="summary-card">
        <div class="card-icon blue"><i class="fas fa-file-alt"></i></div>
        <div class="card-info">
            <h3>{{ $stats['reports_generated'] }}</h3>
            <p>Reports Generated</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon green"><i class="fas fa-download"></i></div>
        <div class="card-info">
            <h3>{{ $stats['downloads'] }}</h3>
            <p>Downloads</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon orange"><i class="fas fa-clock"></i></div>
        <div class="card-info">
            <h3>{{ $stats['scheduled_reports'] }}</h3>
            <p>Scheduled Reports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon purple"><i class="fas fa-archive"></i></div>
        <div class="card-info">
            <h3>{{ $stats['archived_reports'] }}</h3>
            <p>Archived Reports</p>
        </div>
    </div>
</div>

<!-- Filters -->
<div class="table-card" style="margin-bottom:1.5rem;padding:1rem 1.25rem;">
    <form method="GET" action="{{ route('admin.reports.report-history') }}" class="filter-bar" style="margin-bottom:0;flex-wrap:wrap;">
        <input type="text" name="search" placeholder="Search history..." value="{{ request('search') }}" style="padding:0.5rem 0.85rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.85rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;min-width:200px;">
        <select name="action" style="padding:0.5rem 0.85rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.85rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;min-width:140px;">
            <option value="">All Actions</option>
            <option value="generated">Generated</option>
            <option value="downloaded">Downloaded</option>
            <option value="exported">Exported</option>
            <option value="archived">Archived</option>
            <option value="restored">Restored</option>
            <option value="deleted">Deleted</option>
        </select>
        <div style="margin-left:auto;display:flex;gap:0.5rem;">
            <button type="submit" class="btn btn-primary" style="padding:0.5rem 1rem;font-size:0.85rem;"><i class="fas fa-search"></i> Search</button>
            <a href="{{ route('admin.reports.report-history') }}" class="btn btn-secondary" style="padding:0.5rem 1rem;font-size:0.85rem;"><i class="fas fa-undo"></i> Reset</a>
        </div>
    </form>
</div>

<!-- History Table -->
<div class="table-card">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;flex-wrap:wrap;gap:0.75rem;">
        <h3 style="margin:0;"><i class="fas fa-list"></i> Report History</h3>
        <span style="font-size:0.85rem;color:var(--text-muted);">Showing {{ $history->firstItem() ?? 0 }} to {{ $history->lastItem() ?? 0 }} of {{ $history->total() }} results</span>
    </div>
    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Report Name</th>
                    <th>Module</th>
                    <th>Generated By</th>
                    <th>Date Generated</th>
                    <th>Export Format</th>
                    <th>Status</th>
                    <th style="text-align:center;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($history as $entry)
                <tr>
                    <td><span style="font-size:0.8rem;color:var(--text-muted);font-family:monospace;">#RPT-{{ str_pad($entry->report_id ?? 0, 6, '0', STR_PAD_LEFT) }}</span></td>
                    <td><strong>{{ $entry->report->name ?? 'N/A' }}</strong></td>
                    <td><span class="status-badge status-review">{{ ucfirst($entry->report->category ?? 'N/A') }}</span></td>
                    <td>{{ $entry->performedBy->name ?? 'System' }}</td>
                    <td>{{ $entry->performed_at->format('M d, Y H:i') }}</td>
                    <td>
                        @php
                            $export = $entry->report->exports->last();
                            $format = $export?->export_format ?? '-';
                            $formatColors = ['pdf' => 'status-pending', 'excel' => 'status-success', 'print' => 'status-review'];
                        @endphp
                        <span class="status-badge {{ $formatColors[$format] ?? 'status-pending' }}">{{ strtoupper($format) }}</span>
                    </td>
                    <td>
                        @php
                            $actionColors = [
                                'generated' => 'status-review',
                                'downloaded' => 'status-success',
                                'exported' => 'status-warning',
                                'archived' => 'status-pending',
                                'restored' => 'status-success',
                                'deleted' => 'status-inactive',
                            ];
                        @endphp
                        <span class="status-badge {{ $actionColors[$entry->action] ?? 'status-pending' }}">{{ ucfirst($entry->action) }}</span>
                    </td>
                    <td style="text-align:center;">
                        <button class="icon-btn" title="View" onclick="showToast('View report')"><i class="fas fa-eye"></i></button>
                        <button class="icon-btn" title="Download Again" onclick="showToast('Downloading report...')"><i class="fas fa-download"></i></button>
                        <button class="icon-btn" title="Archive" onclick="archiveReport({{ $entry->report_id }})" style="color:var(--warning);"><i class="fas fa-archive"></i></button>
                        <button class="icon-btn" title="Delete" onclick="deleteReport({{ $entry->report_id }})" style="color:var(--danger);"><i class="fas fa-trash"></i></button>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="8" style="text-align:center;padding:2rem;color:var(--text-muted);">No history records found.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div style="margin-top:1rem;display:flex;justify-content:center;">
        {{ $history->links() }}
    </div>
</div>

<!-- Charts -->
<div class="charts-grid" style="margin-top:1.5rem;">
    <div class="chart-card">
        <h3><i class="fas fa-chart-line"></i> Report Generation Trend</h3>
        <div class="chart-wrapper">
            <canvas id="reportTrendChart"></canvas>
        </div>
    </div>
    <div class="chart-card">
        <h3><i class="fas fa-chart-bar"></i> Export Activity</h3>
        <div class="chart-wrapper">
            <canvas id="exportActivityChart"></canvas>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
function archiveReport(id) {
    showToast('Report archived successfully.');
}
function deleteReport(id) {
    if (confirm('Are you sure you want to delete this report?')) {
        showToast('Report deleted successfully.');
    }
}
function exportReport(format) {
    showToast('Exporting history as ' + format.toUpperCase() + '...');
}

document.addEventListener('DOMContentLoaded', function() {
    const trendCtx = document.getElementById('reportTrendChart');
    if (trendCtx) {
        new Chart(trendCtx, {
            type: 'line',
            data: {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                datasets: [{
                    label: 'Reports Generated',
                    data: [12, 19, 15, 25, 22, 30],
                    borderColor: '#F44336',
                    backgroundColor: 'rgba(244, 67, 54, 0.1)',
                    fill: true,
                    tension: 0.4,
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: { y: { beginAtZero: true } },
                plugins: { legend: { display: false } }
            }
        });
    }

    const activityCtx = document.getElementById('exportActivityChart');
    if (activityCtx) {
        new Chart(activityCtx, {
            type: 'bar',
            data: {
                labels: ['PDF', 'Excel', 'Print'],
                datasets: [{
                    label: 'Exports',
                    data: [45, 32, 8],
                    backgroundColor: ['#F44336', '#EF5350', '#D32F2F'],
                    borderRadius: 8,
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: { y: { beginAtZero: true } },
                plugins: { legend: { display: false } }
            }
        });
    }
});
</script>
@endpush
