<?php $__env->startSection('title', 'TripWise — Learning Reports'); ?>

<?php $__env->startSection('content'); ?>
<!-- Breadcrumb -->
<div class="breadcrumb">
    <a href="<?php echo e(route('admin.dashboard')); ?>">Home</a>
    <span>/</span>
    <a href="<?php echo e(route('admin.learning.index')); ?>">Learning Management</a>
    <span>/</span>
    <span>Learning Reports</span>
</div>

<!-- Page Header -->
<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.5rem;flex-wrap:wrap;gap:1rem;">
    <div>
        <h1 style="font-size:1.75rem;color:var(--primary);margin:0 0 0.25rem;">Learning Reports</h1>
        <p style="color:var(--text-muted);font-size:0.9rem;margin:0;">Generate learning-related reports.</p>
    </div>
    <div style="display:flex;gap:0.75rem;flex-wrap:wrap;">
        <button class="btn btn-secondary" onclick="exportReport('pdf')"><i class="fas fa-file-pdf"></i> Export PDF</button>
        <button class="btn btn-secondary" onclick="exportReport('excel')"><i class="fas fa-file-excel"></i> Export Excel</button>
        <button class="btn btn-primary" onclick="window.print()"><i class="fas fa-print"></i> Print Report</button>
    </div>
</div>

<!-- Dashboard Stats Cards -->
<div class="summary-grid">
    <div class="summary-card">
        <div class="card-icon blue"><i class="fas fa-file-alt"></i></div>
        <div class="card-info">
            <h3><?php echo e($stats['generated']); ?></h3>
            <p>Reports Generated</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon green"><i class="fas fa-chart-line"></i></div>
        <div class="card-info">
            <h3><?php echo e($stats['completion']); ?></h3>
            <p>Learning Completion</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon orange"><i class="fas fa-user"></i></div>
        <div class="card-info">
            <h3><?php echo e($stats['driver_reports']); ?></h3>
            <p>Driver Reports</p>
        </div>
    </div>
    <div class="summary-card">
        <div class="card-icon purple"><i class="fas fa-book"></i></div>
        <div class="card-info">
            <h3><?php echo e($stats['module_reports']); ?></h3>
            <p>Module Reports</p>
        </div>
    </div>
</div>

<!-- Filters -->
<div class="table-card" style="margin-bottom:1rem;">
    <form method="GET" action="<?php echo e(route('admin.learning.reports')); ?>" style="display:flex;gap:1rem;align-items:flex-end;flex-wrap:wrap;">
        <div style="flex:1;min-width:200px;">
            <label style="display:block;font-size:0.85rem;font-weight:600;margin-bottom:0.4rem;">Search Reports</label>
            <input type="text" name="search" value="<?php echo e(request('search')); ?>" placeholder="Search by report name..." style="width:100%;padding:0.6rem 1rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.9rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;">
        </div>
        <div style="min-width:180px;">
            <label style="display:block;font-size:0.85rem;font-weight:600;margin-bottom:0.4rem;">Report Type</label>
            <select name="type" style="width:100%;padding:0.6rem 1rem;border:1px solid var(--border);border-radius:0.5rem;font-size:0.9rem;background:var(--white);color:var(--text-dark);font-family:'Inter',sans-serif;">
                <option value="">All Types</option>
                <option value="completion" <?php echo e(request('type') === 'completion' ? 'selected' : ''); ?>>Completion</option>
                <option value="driver" <?php echo e(request('type') === 'driver' ? 'selected' : ''); ?>>Driver</option>
                <option value="module" <?php echo e(request('type') === 'module' ? 'selected' : ''); ?>>Module</option>
                <option value="analytics" <?php echo e(request('type') === 'analytics' ? 'selected' : ''); ?>>Analytics</option>
            </select>
        </div>
        <button type="submit" class="btn btn-secondary"><i class="fas fa-search"></i> Filter</button>
    </form>
</div>

<!-- Reports Table -->
<div class="table-card">
    <h3 style="margin:0 0 1rem;"><i class="fas fa-file-alt"></i> Report History</h3>
    <div style="overflow-x:auto;">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Report Name</th>
                    <th>Report Type</th>
                    <th>Generated Date</th>
                    <th>Generated By</th>
                    <th>Status</th>
                    <th style="text-align:right;">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php $__empty_1 = true; $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                    <tr>
                        <td>#RPT-<?php echo e(str_pad($report->id, 6, '0', STR_PAD_LEFT)); ?></td>
                        <td><strong><?php echo e($report->name); ?></strong></td>
                        <td style="text-transform:capitalize;"><?php echo e($report->report_type); ?></td>
                        <td><?php echo e($report->generated_at ? \Carbon\Carbon::parse($report->generated_at)->format('M d, Y h:i A') : 'N/A'); ?></td>
                        <td><?php echo e($report->generatedBy->name ?? 'System'); ?></td>
                        <td>
                            <span class="item-badge <?php echo e($report->status === 'completed' ? 'badge-success' : ($report->status === 'pending' ? 'badge-warning' : 'badge-danger')); ?>">
                                <?php echo e(ucfirst($report->status)); ?>

                            </span>
                        </td>
                        <td style="text-align:right;">
                            <div style="display:flex;gap:0.5rem;justify-content:flex-end;">
                                <button class="btn btn-sm btn-secondary" title="View"><i class="fas fa-eye"></i></button>
                                <button class="btn btn-sm btn-primary" title="Download PDF"><i class="fas fa-file-pdf"></i></button>
                                <button class="btn btn-sm btn-primary" title="Download Excel"><i class="fas fa-file-excel"></i></button>
                                <button class="btn btn-sm btn-secondary" title="Print" onclick="window.print()"><i class="fas fa-print"></i></button>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                    <tr><td colspan="7" style="text-align:center;color:var(--text-muted);padding:2rem;">No reports found.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
    <div style="margin-top:1rem;">
        <?php echo e($reports->links()); ?>

    </div>
</div>

<!-- Charts -->
<div class="charts-grid" style="margin-top:1.5rem;">
    <div class="chart-card">
        <h3><i class="fas fa-chart-line"></i> Completion Trend</h3>
        <div class="chart-wrapper">
            <canvas id="completionTrendChart"></canvas>
        </div>
    </div>
    <div class="chart-card">
        <h3><i class="fas fa-chart-bar"></i> Learning Report Analytics</h3>
        <div class="chart-wrapper">
            <canvas id="learningReportAnalyticsChart"></canvas>
        </div>
    </div>
</div>

<?php $__env->stopSection(); ?>

<?php $__env->startSection('scripts'); ?>
<script>
function exportReport(format) { showToast('Exporting ' + format.toUpperCase() + ' report...'); }
function showToast(message) {
    const toast = document.getElementById('toast');
    document.getElementById('toastMessage').textContent = message;
    toast.style.display = 'flex';
    setTimeout(() => { toast.style.display = 'none'; }, 3000);
}
document.addEventListener('DOMContentLoaded', function() {
    const chartDefaults = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { labels: { font: { family: "'Poppins', sans-serif" } } } }
    };

    new Chart(document.getElementById('completionTrendChart'), {
        type: 'line',
        data: {
            labels: <?php echo json_encode($completionTrend->pluck('month_num')->toArray()); ?>,
            datasets: [{
                label: 'Completion %',
                data: <?php echo json_encode($completionTrend->pluck('total')->toArray()); ?>,
                borderColor: '#10b981',
                backgroundColor: 'rgba(16,185,129,0.1)',
                fill: true, tension: 0.4, pointRadius: 4, pointBackgroundColor: '#10b981'
            }]
        },
        options: { ...chartDefaults, plugins: { legend: { display: false } } }
    });

    new Chart(document.getElementById('learningReportAnalyticsChart'), {
        type: 'bar',
        data: {
            labels: <?php echo json_encode($reportAnalytics->pluck('report_type')->toArray()); ?>,
            datasets: [{
                label: 'Completion Rate %',
                data: <?php echo json_encode($reportAnalytics->pluck('total')->toArray()); ?>,
                backgroundColor: '#3b82f6',
                borderRadius: 8
            }]
        },
        options: { ...chartDefaults, scales: { y: { beginAtZero: true, max: 100 } } }
    });
});
</script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\ADMIN\Herd\TEAM-3\resources\views/admin/learning/learning-reports.blade.php ENDPATH**/ ?>