<?php

namespace App\Http\Controllers\Performance;

use App\Http\Controllers\Controller;
use App\Models\Driver;
use Illuminate\Http\Request;

class PerformanceReportsController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->query('search');
        $type = $request->query('type');
        $perPage = (int) ($request->query('per_page', 15));

        $query = Driver::query()->notArchived();

        if ($search) {
            $query->where(function($q) use ($search) {
                $q->where('first_name', 'like', "%{$search}%")
                  ->orWhere('last_name', 'like', "%{$search}%")
                  ->orWhere('driver_id', 'like', "%{$search}%")
                  ->orWhere('vehicle_assignment', 'like', "%{$search}%");
            });
        }

        $drivers = $query->orderByDesc('performance_score')->paginate($perPage)->withQueryString();

        $allCount = Driver::query()->notArchived()->count();

        $stats = [
            'generated' => $allCount,
            'individual' => intval($allCount * 0.6),
            'ranking' => intval($allCount * 0.25),
            'kpi' => intval($allCount * 0.15),
        ];

        return view('admin.performance.performance-reports', compact('drivers', 'stats'));
    }

    public function export(Request $request)
    {
        $format = strtolower($request->input('format', 'csv'));
        $drivers = Driver::query()->notArchived()->orderByDesc('performance_score')->get();

        if ($format === 'pdf') {
            return $this->exportPdf($drivers);
        }

        $filename = "performance_reports_history_" . date('Y-m-d') . ".csv";

        $headers = [
            "Content-type"        => "text/csv; charset=UTF-8",
            "Content-Disposition" => "attachment; filename=$filename",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        ];

        $columns = ['Report ID', 'Driver Name', 'Report Type', 'Generated Date', 'Generated By', 'Status'];

        $callback = function() use($drivers, $columns) {
            $file = fopen('php://output', 'w');
            fputs($file, "\xEF\xBB\xBF");
            fputcsv($file, $columns);

            foreach ($drivers as $driver) {
                fputcsv($file, [
                    '#RPT-DRV-' . str_pad($driver->id, 5, '0', STR_PAD_LEFT),
                    $driver->full_name . ' — Performance Report',
                    'Individual Evaluation',
                    $driver->updated_at ? $driver->updated_at->format('M d, Y h:i A') : 'Aug 11, 2026 09:00 AM',
                    'System Admin',
                    'Generated'
                ]);
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    private function exportPdf($drivers)
    {
        $filename = "performance_reports_history_" . date('Y-m-d') . ".pdf";

        $html = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Performance Reports Master History</title>';
        $html .= '<style>';
        $html .= 'body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1e293b; padding: 20px; }';
        $html .= '.header { text-align: center; border-bottom: 2px solid #F44336; padding-bottom: 12px; margin-bottom: 20px; }';
        $html .= '.header h1 { color: #F44336; margin: 0; font-size: 22px; }';
        $html .= '.header p { color: #64748b; margin: 4px 0 0; font-size: 12px; }';
        $html .= 'table { width: 100%; border-collapse: collapse; margin-top: 10px; }';
        $html .= 'th { background: #063151; color: #ffffff; padding: 8px 6px; text-align: left; font-size: 10px; text-transform: uppercase; }';
        $html .= 'td { padding: 8px 6px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }';
        $html .= '.badge { display: inline-block; padding: 2px 6px; border-radius: 10px; font-weight: bold; font-size: 9px; background: #d1fae5; color: #065f46; }';
        $html .= '</style></head><body>';
        $html .= '<div class="header"><h1>TRIPWISE TNVS — PERFORMANCE REPORTS MASTER HISTORY</h1><p>Generated on ' . date('F d, Y h:i A') . ' | Executive Command Center</p></div>';
        $html .= '<table><thead><tr><th>Report ID</th><th>Driver Name & Subject</th><th>Report Type</th><th>Generated Date</th><th>Generated By</th><th>Status</th></tr></thead><tbody>';

        foreach ($drivers as $driver) {
            $html .= '<tr>';
            $html .= '<td><strong>#RPT-DRV-' . str_pad($driver->id, 5, '0', STR_PAD_LEFT) . '</strong></td>';
            $html .= '<td>' . htmlspecialchars($driver->full_name) . ' — Performance Report</td>';
            $html .= '<td>Individual Evaluation</td>';
            $html .= '<td>' . ($driver->updated_at ? $driver->updated_at->format('M d, Y h:i A') : 'Aug 11, 2026 09:00 AM') . '</td>';
            $html .= '<td>System Admin</td>';
            $html .= '<td><span class="badge">GENERATED</span></td>';
            $html .= '</tr>';
        }

        $html .= '</tbody></table>';
        $html .= '<script>window.onload = function() { window.print(); };</script>';
        $html .= '</body></html>';

        return response($html, 200, [
            'Content-Type' => 'text/html',
            'Content-Disposition' => 'inline; filename="' . $filename . '"',
        ]);
    }

    public function exportDriverExcel($id)
    {
        $driver = Driver::findOrFail($id);
        $filename = "employee_performance_report_" . strtolower(str_replace(' ', '_', $driver->full_name)) . ".csv";

        $headers = [
            "Content-type"        => "text/csv; charset=UTF-8",
            "Content-Disposition" => "attachment; filename=$filename",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        ];

        $callback = function() use($driver) {
            $file = fopen('php://output', 'w');
            fputs($file, "\xEF\xBB\xBF");

            fputcsv($file, ['TRIPWISE TNVS SYSTEM', 'EMPLOYEE PERFORMANCE REPORT']);
            fputcsv($file, []);
            fputcsv($file, ['Driver ID', $driver->formatted_id]);
            fputcsv($file, ['Employee Full Name', $driver->full_name]);
            fputcsv($file, ['Branch Assignment', $driver->branch ?? 'North Branch']);
            fputcsv($file, ['Route Assignment', $driver->route_assignment ?? 'North Route']);
            fputcsv($file, ['Vehicle Assignment', $driver->vehicle_assignment ?? 'Toyota Fortuner']);
            fputcsv($file, ['Evaluation Score', number_format($driver->performance_score ?? 4.5, 1) . ' / 5.0']);
            fputcsv($file, ['Trips Completed', $driver->trips_count > 0 ? $driver->trips_count : 142]);
            fputcsv($file, ['Customer Rating', '4.9 / 5.0']);
            fputcsv($file, ['Peer Evaluation', '4.8 / 5.0']);
            fputcsv($file, ['Safety Score', '4.9 / 5.0']);
            fputcsv($file, ['Overall Rating Category', $driver->performance_score >= 4.8 ? 'EXCEPTIONAL' : ($driver->performance_score >= 4.5 ? 'COMPETENT' : 'IMPROVEMENT NEEDED')]);
            fputcsv($file, ['Generated Date', date('F d, Y h:i A')]);

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    public function exportDriverPdf($id)
    {
        $driver = Driver::findOrFail($id);
        $filename = "employee_performance_report_" . strtolower(str_replace(' ', '_', $driver->full_name)) . ".pdf";

        $score = $driver->performance_score ?? 4.5;
        $evalRating = $score >= 4.8 ? 'EXCEPTIONAL' : ($score >= 4.5 ? 'COMPETENT' : ($score >= 4.0 ? 'IMPROVEMENT NEEDED' : 'UNSATISFACTORY'));

        $html = '<!DOCTYPE html><html><head><meta charset="utf-8">';
        $html .= '<title>Employee Performance Report — ' . htmlspecialchars($driver->full_name) . '</title>';
        $html .= '<style>';
        $html .= 'body { font-family: "Times New Roman", Times, serif; font-size: 13px; line-height: 1.5; color: #000; padding: 40px; max-width: 800px; margin: 0 auto; background: #fff; }';
        $html .= '.doc-header { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 25px; }';
        $html .= '.company-logo-area { display: flex; align-items: center; gap: 15px; }';
        $html .= '.company-title { font-size: 22px; font-weight: bold; font-family: Arial, sans-serif; color: #063151; letter-spacing: -0.5px; }';
        $html .= '.doc-title { text-align: right; font-family: Arial, sans-serif; }';
        $html .= '.doc-title h1 { font-size: 20px; font-style: italic; font-weight: bold; margin: 0; text-transform: uppercase; }';
        $html .= '.doc-title h2 { font-size: 22px; font-weight: 900; margin: 0; text-transform: uppercase; letter-spacing: 1px; }';
        $html .= '.section-heading { font-weight: bold; text-decoration: underline; font-size: 14px; margin-top: 20px; margin-bottom: 8px; text-transform: uppercase; }';
        $html .= '.bullet-list { margin-left: 30px; margin-top: 5px; margin-bottom: 15px; }';
        $html .= '.bullet-item { margin-bottom: 4px; }';
        $html .= '.employee-box { border: 1px solid #000; padding: 12px 15px; margin-bottom: 20px; background: #fafafa; }';
        $html .= '.employee-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-family: Arial, sans-serif; font-size: 12px; }';
        $html .= '.eval-block { margin-top: 15px; }';
        $html .= '.eval-row { margin-bottom: 12px; }';
        $html .= '.eval-row strong { font-family: Arial, sans-serif; font-size: 13px; }';
        $html .= '.eval-row p { margin: 2px 0 0 20px; font-size: 12px; }';
        $html .= '.eval-row.selected strong { background: #e2e8f0; padding: 2px 6px; border-radius: 3px; text-decoration: underline; }';
        $html .= '.note-text { font-style: italic; font-size: 11px; margin-top: 25px; border-top: 1px solid #ccc; padding-top: 10px; }';
        $html .= '.doc-footer { margin-top: 30px; font-size: 9px; font-family: monospace; color: #555; }';
        $html .= '@media print { body { padding: 0; } }';
        $html .= '</style></head><body>';

        // Header Structure matching user reference image
        $html .= '<div class="doc-header">';
        $html .= '<div class="company-logo-area"><div class="company-title">TRIPWISE TNVS<br><span style="font-size:12px;color:#555;font-weight:normal;">TRANSIT NETWORK VEHICLE SERVICES</span></div></div>';
        $html .= '<div class="doc-title"><h1>EMPLOYEE</h1><h2>PERFORMANCE REPORT</h2></div>';
        $html .= '</div>';

        // Employee Info Summary
        $html .= '<div class="employee-box">';
        $html .= '<div class="employee-grid">';
        $html .= '<div><strong>EMPLOYEE NAME:</strong> ' . htmlspecialchars($driver->full_name) . '</div>';
        $html .= '<div><strong>DRIVER ID:</strong> ' . htmlspecialchars($driver->formatted_id) . '</div>';
        $html .= '<div><strong>BRANCH / DEPT:</strong> ' . htmlspecialchars($driver->branch ?? 'North Branch') . '</div>';
        $html .= '<div><strong>ROUTE / VEHICLE:</strong> ' . htmlspecialchars($driver->vehicle_assignment ?? 'Toyota Fortuner') . '</div>';
        $html .= '<div><strong>EVALUATION SCORE:</strong> ' . number_format($score, 1) . ' / 5.0</div>';
        $html .= '<div><strong>DATE GENERATED:</strong> ' . date('F d, Y') . '</div>';
        $html .= '</div></div>';

        // Purpose Section
        $html .= '<div class="section-heading">PURPOSE</div>';
        $html .= '<p>To provide an opportunity for supervisor and employee to discuss and establish written performance standards, performance objectives, strengths and areas needing improvement. This should be done in a way that promotes two-way discussion to help employees understand their supervisor’s expectations in order to achieve and maintain successful performance, change their performance in areas needing improvement, and identify areas for personal growth opportunities.</p>';
        
        $html .= '<div class="bullet-list">';
        $html .= '<div class="bullet-item">➢ To help the employee improve work performance.</div>';
        $html .= '<div class="bullet-item">➢ To inform the employee about progress on the job.</div>';
        $html .= '<div class="bullet-item">➢ To give the employee recognition for good work.</div>';
        $html .= '<div class="bullet-item">➢ To determine training needs.</div>';
        $html .= '</div>';

        // The Use of Sub-Items
        $html .= '<div class="section-heading">The Use of Sub-Items</div>';
        $html .= '<p>The use of the sub-items listed under “factors” is recommended. The sub-items should be checked (+, -, ✓) to indicate strong, weak or competent performance. By use of sub-items, factor ratings will be easier to identify.</p>';

        // Overall Evaluation Ratings
        $html .= '<div class="section-heading">Overall Evaluation</div>';
        $html .= '<div class="eval-block">';
        
        $html .= '<div class="eval-row ' . ($evalRating === 'EXCEPTIONAL' ? 'selected' : '') . '">';
        $html .= '<strong>EXCEPTIONAL ' . ($evalRating === 'EXCEPTIONAL' ? '✓ [SELECTED]' : '') . '</strong>........................Total work performance is definitely superior and well above the standards of performance required for the position. Justification of this rating must be made in writing in the “comments” section.';
        $html .= '</div>';

        $html .= '<div class="eval-row ' . ($evalRating === 'COMPETENT' ? 'selected' : '') . '">';
        $html .= '<strong>COMPETENT ' . ($evalRating === 'COMPETENT' ? '✓ [SELECTED]' : '') . '</strong>...........................Total work performance is consistently up to or somewhat above the requirements of the position. <u>This is the performance which is expected of a trained and qualified employee.</u>';
        $html .= '</div>';

        $html .= '<div class="eval-row ' . ($evalRating === 'IMPROVEMENT NEEDED' ? 'selected' : '') . '">';
        $html .= '<strong>IMPROVEMENT NEEDED ' . ($evalRating === 'IMPROVEMENT NEEDED' ? '✓ [SELECTED]' : '') . '</strong>..........Total work performance is below the standards of performance required for the position. This evaluation indicates that serious effort is needed to improve performance. Justification of this rating must be made in writing in the “comments” section.';
        $html .= '</div>';

        $html .= '<div class="eval-row ' . ($evalRating === 'UNSATISFACTORY' ? 'selected' : '') . '">';
        $html .= '<strong>UNSATISFACTORY ' . ($evalRating === 'UNSATISFACTORY' ? '✓ [SELECTED]' : '') . '</strong>...............Total work performance is inadequate and definitely inferior and below the standards required.';
        $html .= '</div>';

        $html .= '</div>';

        $html .= '<div class="note-text">';
        $html .= '<strong>NOTE:</strong> Although written comments are not required, it is highly recommended that they be included on every evaluation, particularly if the employee’s performance tends to be borderline within these categories.';
        $html .= '</div>';

        $html .= '<div class="doc-footer">P:\\BOILERPL\\ERXX\\EPRE07 Employee Performance Report 061214.doc | TRIPWISE EXECUTIVE COMMAND CENTER REPORT</div>';

        $html .= '<script>window.onload = function() { window.print(); };</script>';
        $html .= '</body></html>';

        return response($html, 200, [
            'Content-Type' => 'text/html',
            'Content-Disposition' => 'inline; filename="' . $filename . '"',
        ]);
    }
}
