<?php

namespace App\Http\Controllers\Performance;

use App\Http\Controllers\Controller;
use App\Models\Driver;
use Illuminate\Http\Request;

class PerformanceReportsController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->query('search');
        $type = $request->query('type');
        $perPage = (int) ($request->query('per_page', 15));

        $query = Driver::query()->notArchived();

        if ($search) {
            $query->where(function($q) use ($search) {
                $q->where('first_name', 'like', "%{$search}%")
                  ->orWhere('last_name', 'like', "%{$search}%")
                  ->orWhere('driver_id', 'like', "%{$search}%")
                  ->orWhere('vehicle_assignment', 'like', "%{$search}%");
            });
        }

        $drivers = $query->orderByDesc('performance_score')->paginate($perPage)->withQueryString();

        $allCount = Driver::query()->notArchived()->count();

        $stats = [
            'generated' => $allCount,
            'individual' => intval($allCount * 0.6),
            'ranking' => intval($allCount * 0.25),
            'kpi' => intval($allCount * 0.15),
        ];

        return view('admin.performance.performance-reports', compact('drivers', 'stats'));
    }

    public function export(Request $request)
    {
        $format = strtolower($request->input('format', 'csv'));
        $drivers = Driver::query()->notArchived()->orderByDesc('performance_score')->get();

        if ($format === 'pdf') {
            return $this->exportPdf($drivers);
        }

        $filename = "performance_reports_history_" . date('Y-m-d') . ".csv";

        $headers = [
            "Content-type"        => "text/csv; charset=UTF-8",
            "Content-Disposition" => "attachment; filename=$filename",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        ];

        $columns = ['Report ID', 'Driver Name', 'Report Type', 'Generated Date', 'Generated By', 'Status'];

        $callback = function() use($drivers, $columns) {
            $file = fopen('php://output', 'w');
            fputs($file, "\xEF\xBB\xBF");
            fputcsv($file, $columns);

            foreach ($drivers as $driver) {
                fputcsv($file, [
                    '#RPT-DRV-' . str_pad($driver->id, 5, '0', STR_PAD_LEFT),
                    $driver->full_name . ' — Performance Report',
                    'Individual Evaluation',
                    $driver->updated_at ? $driver->updated_at->format('M d, Y h:i A') : 'Aug 11, 2026 09:00 AM',
                    'System Admin',
                    'Generated'
                ]);
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    private function exportPdf($drivers)
    {
        $filename = "performance_reports_history_" . date('Y-m-d') . ".pdf";

        $html = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Performance Reports Master History</title>';
        $html .= '<style>';
        $html .= 'body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1e293b; padding: 20px; }';
        $html .= '.header { text-align: center; border-bottom: 2px solid #F44336; padding-bottom: 12px; margin-bottom: 20px; }';
        $html .= '.header h1 { color: #F44336; margin: 0; font-size: 22px; }';
        $html .= '.header p { color: #64748b; margin: 4px 0 0; font-size: 12px; }';
        $html .= 'table { width: 100%; border-collapse: collapse; margin-top: 10px; }';
        $html .= 'th { background: #063151; color: #ffffff; padding: 8px 6px; text-align: left; font-size: 10px; text-transform: uppercase; }';
        $html .= 'td { padding: 8px 6px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }';
        $html .= '.badge { display: inline-block; padding: 2px 6px; border-radius: 10px; font-weight: bold; font-size: 9px; background: #d1fae5; color: #065f46; }';
        $html .= '</style></head><body>';
        $html .= '<div class="header"><h1>TRIPWISE TNVS — PERFORMANCE REPORTS MASTER HISTORY</h1><p>Generated on ' . date('F d, Y h:i A') . ' | Executive Command Center</p></div>';
        $html .= '<table><thead><tr><th>Report ID</th><th>Driver Name & Subject</th><th>Report Type</th><th>Generated Date</th><th>Generated By</th><th>Status</th></tr></thead><tbody>';

        foreach ($drivers as $driver) {
            $html .= '<tr>';
            $html .= '<td><strong>#RPT-DRV-' . str_pad($driver->id, 5, '0', STR_PAD_LEFT) . '</strong></td>';
            $html .= '<td>' . htmlspecialchars($driver->full_name) . ' — Performance Report</td>';
            $html .= '<td>Individual Evaluation</td>';
            $html .= '<td>' . ($driver->updated_at ? $driver->updated_at->format('M d, Y h:i A') : 'Aug 11, 2026 09:00 AM') . '</td>';
            $html .= '<td>System Admin</td>';
            $html .= '<td><span class="badge">GENERATED</span></td>';
            $html .= '</tr>';
        }

        $html .= '</tbody></table>';
        $html .= '<script>window.onload = function() { window.print(); };</script>';
        $html .= '</body></html>';

        return response($html, 200, [
            'Content-Type' => 'text/html',
            'Content-Disposition' => 'inline; filename="' . $filename . '"',
        ]);
    }
}
